---
- hosts: servers
  become: true
  become_user: root
  tasks:

  - name: clone repo
    git:
      repo: 'https://github.com/max-conroy/Per-Scholas-Capstone-Project-1.git'
      dest: /home/osboxes

  - name: start kubernetes deployment and service using yml file
    shell: kubectl apply -f /home/osboxes/Per-Scholas-Capstone-Project-1/kubernetes.yml

  - name: scale up
    shell: kubectl scale deployment.apps/capstone1deploy --replicas=5
