apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone1deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone1app
  template:
    metadata:
      labels:
        app: capstone1app
    spec:
      containers:
      - name: capstone1container
        image: conroy3644/capstone1-webapp:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: capstone1service
spec:
  type: LoadBalancer
  selector:
    app: capstone1app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
      name: http
