apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone1deploy
  labels:
    app: capstone1app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone1app
  template:
    metadata:
      labels:
        app: capstone1app
    spec:
      containers:
      - name: capstone1container
        image: conroy3644/capstone1-webapp:latest
        ports:
        - containerPort: 7080

---

apiVersion: v1
kind: Service
metadata:
  name: capstone1service
spec:
  type: NodePort
  selector:
    app: capstone1app
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 7080
      nodePort: 31000
